version: '2'
plugins:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  reek:
    enabled: true
exclude_patterns:
  - services/app/babel.config.js
  - services/app/app/controllers/concerns/flash_helper.rb
  - services/app/config/initializers/simple_form_bootstrap.rb
