---
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.4
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Naming/AccessorMethodName:
  Description: Check the naming of accessor methods for get_/set_.
  Enabled: false

Style/DocumentationMethod:
  RequireForNonPublicMethods: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
