---
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - 'bin/**'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/DocumentationMethod:
  RequireForNonPublicMethods: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*.rb'

Metrics/LineLength:
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'
  Max: 150

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'config/initializers/simple_form_bootstrap.rb'

Metrics/ParameterLists:
  Exclude:
    - 'app/controllers/concerns/flash_helper.rb'

Metrics/MethodLength:
  Max: 30

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/Output:
  Exclude:
    - 'db/seeds.rb'

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
