# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'rails', '~> 6.0.0'

gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'config'
gem 'enumerize'
gem 'kaminari'
gem 'pg'
gem 'puma', '~> 3.11'
gem 'state_machines'
gem 'state_machines-activerecord'
gem 'webpacker', '~> 4.0'

## frontend

gem 'jbuilder', '~> 2.7'
gem 'react-rails', '~> 2.6'
gem 'sassc-rails'
gem 'simple_form'
gem 'slim-rails'
# gem 'sass-rails', '~> 5'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'dotenv-rails'
  gem 'faker'
  gem 'pry-byebug'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'slim_lint'
end

group :development do
  gem 'awesome_print'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rubocop'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
end

group :test do
  gem 'capybara'
  gem 'minitest-power_assert'
  gem 'selenium-webdriver'
  gem 'webdrivers', '~> 4.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
