---
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  host: localhost
  user: <%= ASDF.db_username %>
  database: time_tracker_development
  port: <%= ASDF.db_port %>

test:
  <<: *default
  host: <%= ASDF.db_hostname %>
  user: <%= ASDF.db_username %>
  database: time_tracker_test
  port: <%= ASDF.db_port %>

production:
  <<: *default
  host: <%= ASDF.db_hostname %>
  user: <%= ASDF.db_username %>
  database: <%= ASDF.db_name %>
  password: <%= ASDF.db_password %>
